Controllers/GitHubJobsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using JobPortal.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace JobPortal.Controllers
{
    public class GitHubJobsController : Controller
    {
        public IActionResult Index()
        {
            string url = "https://jobs.github.com/positions.json?page=1";
            var request = (System.Net.HttpWebRequest)System.Net.WebRequest.Create(url);
            request.Method = "GET";

            var content = string.Empty;
            using (var response = (System.Net.HttpWebResponse)request.GetResponse())
            {
                using (var stream = response.GetResponseStream())
                {
                    using (var sr = new StreamReader(stream))
                    {
                        content = sr.ReadToEnd();
                    }
                }
            }

            IList<GitHubJobsResponseModel> gitjobs= JsonConvert.DeserializeObject<List<GitHubJobsResponseModel>>(content);

            return View(gitjobs);
        }

        
    }
    }

Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using JobPortal.Models;
using JobPortal.ViewModels.Home;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.ServiceBus;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace JobPortal.Controllers
{
    public class JobController : Controller
    {
        private readonly ILogger _logger;
        private readonly ApplicationDbContext _context;
        private UserManager<User> _userManager;

        private readonly QueueClient _queueClient;
        private readonly IConfiguration _configuration;
        private const string QUEUE_NAME = "simplequeue";

        public JobController(ApplicationDbContext context, UserManager<User> userManager, ILogger<JobController> logger, IConfiguration config)
        {
            _logger = logger;
            _context = context;
            _userManager = userManager;

        }

        [Route("jobs")]
        public IActionResult Index()
        {
            var jobs = _context.Jobs.ToList();

            return View(jobs);
        }

        [Route("jobs/create")]
        [Authorize(Roles = "Employer")]
        public IActionResult Create()
        {
            return View();
        }

        [Route("jobs/save")]
        [Authorize(Roles = "Employer")]
        [HttpPost]
        public async Task<IActionResult> Save(Job model)
        {
            #region Comment
            /*
            if (ModelState.IsValid)
            {
                TempData["type"] = "success";
                TempData["message"] = "Job posted successfully";
                //_logger.LogInformation(model.ToString());
                var user = await _userManager.GetUserAsync(HttpContext.User);
                model.User = user;
                _context.Jobs.Add(model);

                await _context.SaveChangesAsync();

                return RedirectToActionPermanent("Index", "Home");
            }
            */
            #endregion

            if(ModelState.IsValid)
            {
                TempData["type"] = "success";
                TempData["message"] = "Jobs posted successfully";
                using (var httpCllient = new HttpClient())
                {
                    httpCllient.DefaultRequestHeaders.Accept.Clear();
                    httpCllient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    httpCllient.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("gzip"));

                    var data = new Dictionary<string, string>
                {
                    { "title", model.Title},
                    { "description", model.Description },
                    { "location", model.Location },
                    { "type", model.Type},
                    { "createdat", model.CreatedAt.ToString() },
                    { "lastdate", model.LastDate.ToString()},
                    { "companyname", model.CompanyName },
                    { "companydescription", model.CompanyDescription},
                    { "website", model.Website }



                };

                var httpContent = new StringContent(JsonConvert.SerializeObject(data), System.Text.Encoding.UTF8, "application/json");

                    // POST the object to the specified URI
                    var response = await httpCllient.PostAsync("https://caswebapi13082020.azurewebsites.net/api/job/update", httpContent);

                    //Read back the answer from server
                    var responseString = await response.Content.ReadAsStringAsync();

                    // deserialize using json
                    OperationResult<AccessToken> result = JsonConvert.DeserializeObject<OperationResult<AccessToken>>(responseString);
                    if (result.Succeeded)
                    {

                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Invalid login attempt");
                        return View(model);
                    }




                }





            }

            return View("Create", model);
        }

        [HttpPost]
        //[Authorize(Roles = "Employee")]
        public async Task<IActionResult> Apply(int id)
        {
            var job = _context.Jobs.SingleOrDefault(x => x.Id == id);
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if(user == null)
            {
                return RedirectToActionPermanent("Login", "Account");
            }
            else
            {
                if(!User.IsInRole("Employee"))
                {
                    TempData["message"] = "You can't do this action";
                    return RedirectToActionPermanent("JobDetails", "Home", new { id });
                }
            }
            var apply = new Applicant
            {
                User = user,
                Job = job,
                CreatedAt = DateTime.Now
            };

            _context.Applicants.Add(apply);

            await _context.SaveChangesAsync();

            return RedirectToActionPermanent("JobDetails", "Home", new { id });
        }

        [Route("mark-as-filled/{id}")]
        //[Authorize(Roles = "Employer")]
        public async Task<IActionResult> MarkAsFilled(int id)
        {
            var job = _context.Jobs.SingleOrDefault(x => x.Id == id);
            job.isFilled = true;
            _context.Jobs.Update(job);
            await _context.SaveChangesAsync();

            return RedirectToActionPermanent("Index", "Dashboard");
        }
        
        [HttpPost]
        [Authorize(Roles = "Employer")]
        [Route("employer/jobs/{id}/destroy")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Destroy(int id)
        {
            var job = _context.Jobs.SingleOrDefault(x => x.Id == id);
            if(job == null)
            {
                return NotFound();
            }

            _context.Jobs.Remove(job);
            await _context.SaveChangesAsync();

            TempData["type"] = "success";
            TempData["message"] = "Job deleted successfully";

            return RedirectToActionPermanent("Index", "Dashboard");
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Net.Http;
@using JobPortal.ViewModels.Home
@using Microsoft.AspNetCore.Http

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Home - Job Portal</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet"
          href="~/vendor/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet"
          href="~/vendor/font-awesome/css/font-awesome.min.css">
    <!-- Google fonts - Roboto for copy, Montserrat for headings-->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,700">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Montserrat:400,700">
    <!-- owl carousel-->
    <link rel="stylesheet"
          href="~/vendor/owl.carousel/assets/owl.carousel.css">
    <link rel="stylesheet"
          href="~/vendor/owl.carousel/assets/owl.theme.default.css">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="~/css/style.default.css"
          id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="~/css/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="favicon.png">
    <!-- Tweaks for older IEs-->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
    @RenderSection("Stylesheets", required: false)
    <script src="~/lib/jquery/jquery.js"></script>
</head>

<body>
    <script type="text/javascript">
        $(document).ready(function () {
            //$.ajax({
            //    url: 'api/serviceapi',
            //    type: 'GET',
            //    dataType: 'json',
            //    success: function (data, textStatus, xhr) {
            //        console.log(data);

            //    },
            //    error: function (xhr, textStatus, errorThrown) {
            //        console.log('Error in Operation');
            //    }
            //});

            var location = $('.location-nav a:first-child');
            location.css({ 'pointer-events': 'none' });

            $.ajax({
                url: '/ip-geolocation',
                type: 'GET',
                dataType: 'json',
                success: function (data, textStatus, xhr) {
                    if (data != null && data !== undefined && data != null) {
                        if (data["status"] == "success") {
                            location.fadeOut(300, function () {
                                location.text(data['country']).fadeIn(300);
                            });
                        }
                    }
                },
                error: function (xhr, textStatus, errorThrown) {
                    console.log('Error in Operation');
                }
            });
        });
    </script>
    <header class="header">
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a href="/" class="navbar-brand">
                    <img src="~/img/logo-small.png" alt="logo" class="d-none d-lg-block">
                    <span class="sr-only">Home</span>
                </a>
                <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                        class="navbar-toggler navbar-toggler-right">
                    Menu<i class="fa fa-bars"></i>
                </button>
                <div id="navbarSupportedContent" class="collapse navbar-collapse">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a href="/" class="nav-link">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">Contact</a>
                        </li>
                        @{
                            UserWithRoleDto user = Context.Session.GetObjectFromJson<UserWithRoleDto>("userwithroles");
                        }

                        @if (user != null)
                        {
                            if (user.Roles.Where(x => x.Name == "Employer").Count() > 0)// HttpContext this.User.IsInRole("Employer") && SignInManager.IsSignedIn(User))
                            {

                                <form method="post" style="display: none;" id="logout-form" asp-controller="Account" asp-action="Logout"></form>
                                <li class="nav-item dropdown">
                                    <a id="clientZone" href="#" data-toggle="dropdown"
                                       aria-haspopup="true" aria-expanded="false"
                                       class="nav-link dropdown-toggle has-img mb-3 mb-lg-0 mt-3 mt-lg-0">
                                        <div class="client-menu-image">
                                            <div class="inner">
                                                <img src="#"
                                                     alt=""
                                                     class="img-fluid">
                                            </div>
                                        </div>
                                        @user.User.FirstName - @user.User.LastName
                                    </a>
                                    <div aria-labelledby="clientZone" class="dropdown-menu">
                                        <a asp-controller="Dashboard" asp-action="Index" class="dropdown-item">Dashboard</a>
                                        <a asp-controller="Dashboard" asp-action="Applicants" class="dropdown-item">Applicants </a>
                                        <a asp-controller="Job" asp-action="Create" class="dropdown-item">
                                            Post a new job
                                        </a>
                                        <a href="#" class="dropdown-item" onclick="document.getElementById('logout-form').submit();">Logout</a>
                                    </div>
                                </li>

                            }
                            else if (user.Roles.Where(x => x.Name == "Employee").Count() > 0)//this.User.IsInRole("Employee") && SignInManager.IsSignedIn(User))
                            {
                                <form method="post" style="display: none;" id="logout-form" asp-controller="Account" asp-action="Logout"></form>
                                <li class="nav-item dropdown">
                                    <a id="clientZone" href="#" data-toggle="dropdown"
                                       aria-haspopup="true" aria-expanded="false"
                                       class="nav-link dropdown-toggle has-img mb-3 mb-lg-0 mt-3 mt-lg-0">
                                        <div class="client-menu-image">
                                            <div class="inner">
                                                <img src="#" alt="" class="img-fluid">
                                            </div>
                                        </div>
                                        @user.User.FirstName @user.User.LastName
                                    </a>
                                    <div aria-labelledby="clientZone" class="dropdown-menu">
                                        <a asp-controller="Account" asp-action="EditProfile" class="dropdown-item">Edit Profile</a>
                                        <a asp-controller="GitHubJobs" asp-action="Index" class="dropdown-item">Git Hub Jobs</a>
                                        <a href="#" class="dropdown-item" onclick="document.getElementById('logout-form').submit();">Logout</a>
                                    </div>
                                </li>

                            }
                        }
                        else
                        {
                            <li class="nav-item dropdown">
                                <a id="pages" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                                   class="nav-link dropdown-toggle">
                                    <i class="fa fa-signing"></i>Register
                                </a>
                                <div aria-labelledby="pages" class="dropdown-menu">
                                    <a asp-controller="Account" asp-action="EmployeeRegister" class="dropdown-item">Employee</a>
                                    <a asp-controller="Account" asp-action="EmployerRegister" class="dropdown-item">Employers</a>
                                </div>
                            </li>
                            <li class="nav-item" style="color: #fff">
                                <a asp-controller="Account" asp-action="Login" class="btn navbar-btn btn-outline-light mb-5 mb-lg-0">
                                    <i class="fa fa-sign-in"></i>Login
                                </a>
                            </li>
                            <li class="nav-item" style="color: #fff">

                                @*<a asp-controller="Account" asp-action="Login" class="btn navbar-btn btn-outline-light mb-5 mb-lg-0">
                                        <i class="fa fa-sign-in"></i>Login
                                    </a>*@
                            </li>
                        }

                        <li class="nav-item location-nav">
                            <a href="#" class="nav-link">Loading Location...</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <partial name="_CookieConsentPartial" />
        @if (!string.IsNullOrEmpty(TempData["message"] as string))
        {
            if (TempData["type"] as string == "sucess")
            {
                <div class="alert alert-success">
                    @TempData["message"]
                </div> }
            else
            {
                <div class="alert alert-warning">
                    @TempData["message"]
                </div>}
        }
        @RenderBody()
    </div>

    <footer class="footer">
        <div class="footer__block">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-12 mb-5">
                        <h4 class="h5">About Jobs</h4>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus magna. Cras in mi at felis
                            aliquet congue.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer__copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 text-md-left text-center">
                        <p>&copy;2019 Jobs</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/popper.js/umd/popper.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/vendor/jquery.cookie/jquery.cookie.js"></script>
    <script src="~/vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="~/vendor/bootstrap-select/js/bootstrap-select.min.js"></script>
    <script src="~/js/front.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>